### ISSUE TITLE
-v/--version flag does not print tool's name

### ISSUE THREAD

**Issue by lyu4321** [mqnguyen5/mini-ssg#1]
"Does the -v or --version flag print the tool's name and version?" 

Currently, when I run "node mini-ssg.js -v" or "node mini-ssg.js -version", it only prints 1.0.0 without the tool name.

**Comment by mqnguyen5** [comment]
As stated in [yargs](https://github.com/yargs/yargs/blob/master/docs/api.md#versionoption-description-version) documentation:
> If no arguments are passed to version (.version()), yargs will parse the package.json of your module and use its version value.

I believe that's why it only prints out the version number. As for the name, I will try to think of a way to include it in `version()` arguments

**Comment by mqnguyen5** [comment]
I have update the code to include tool name and version number when running `-v` or `--version`. Thanks for spotting it!
