### ISSUE TITLE
Add --config support

### ISSUE THREAD

**Issue by minhhang107** [mqnguyen5/mini-ssg#12]
Hi Quan, I would like to add a new feature for your tool: support for config file.
I'll implement the following:

- [x] Add new flag -c / --config to accept a JSON config file
- [x] Make a clean exit with proper message when appropriate
- [x] Ignore other options when -c / --config is used
- [x] Ignore options in the config file that the tool does not support
- [x] Set options to default if not provided in config file
- [x] Update Readme accordingly

Let me know what you think about this.

**Comment by mqnguyen5** [comment]
Sure, you can begin working on the feature whenever you want.
