### ISSUE TITLE
-i/--input flag does not work for filenames that have a space

### ISSUE THREAD

**Issue by lyu4321** [mqnguyen5/mini-ssg#2]
For example, if I run "node mini-ssg.js -i Sherlock-Holmes-Selected-Stories/Silver Blaze.txt", I will get an error message although the file exists because the filename contains a space.

**Comment by mqnguyen5** [comment]
A temporary solution I can think of at the moment is change the type of option `-i` into `array` and use `Array.join(" ")` to process `argv.input`. Will make the change as soon as possible so you can re-test it!

**Comment by mqnguyen5** [comment]
I have update the code. Please re-run the test and see if it works.

**Comment by lyu4321** [comment]
Looks good :)
