### ISSUE TITLE
Improving formatting of the generated HTML

### ISSUE THREAD

**Issue by lyu4321** [mqnguyen5/mini-ssg#3]
I really like that you can generate all the html from your js code rather than using an html template. It seems really efficient. One thing is that the formatting of the generated html is a little messy. Perhaps something to improve if you have time. 

![htmlformatting](https://user-images.githubusercontent.com/59708190/133718896-8e6efb83-3005-4a39-b2c1-f1ef85597f83.PNG)

For example, the indentation is a little weird and the entire body is all clumped together, which could be separated for better readability.

**Comment by mqnguyen5** [comment]
Thanks for the notice. That is because I'm using the package [create-html](https://github.com/sethvincent/create-html), which automatically generates the necessary html content for me without any formatting. I might have to think of a different way to generate my HTML content in a future update.
