### ISSUE TITLE
Split up usage in README to give more info

### ISSUE THREAD

**Issue by humphd** [mqnguyen5/mini-ssg#5]
The current [Usage](https://github.com/mqnguyen5/mini-ssg#usage) section in the README should be expanded.  You list examples of command lines people can use, but don't explain any of it.  I would show how these various options work.

**Comment by mqnguyen5** [comment]
I made a few changes in the [Usage](https://github.com/mqnguyen5/mini-ssg#usage) section to include explanation of how each command works. Do you mind checking it again to see if it's ok now?

**Comment by humphd** [comment]
Yeah, that's better 👍
