### ISSUE TITLE
Exit on error cases

### ISSUE THREAD

**Issue by humphd** [mqnguyen5/mini-ssg#6]
You have code to print an error message, but it would be good to expand this so that the program exists with an error code:

```js
    if (!existsSync(inputPath)) {
        console.log("File/folder's path does not exist.");
        return process.exit(1);
    }
```

This will cause the program to inform the OS/shell that things didn't work (non-zero exit code).

**Comment by humphd** [comment]
You can do a similar thing here: https://github.com/mqnguyen5/mini-ssg/blob/main/utils/processInput.js#L61.  That error message should be improved, too (e.g., 'Unable to create dist folder').  You might want to ignore the error case if the folder doesn't exist when removing, since you are about to create it anyway.

**Comment by mqnguyen5** [comment]
Is there a way to differentiate the errors? I mean, the `try catch` block wraps both the creation and removing functions and catch both of their errors if one of them fails right? Or simply just changing the `console.log(err)` into a proper error message like "Unable to create 'dist' folder" is enough?

**Comment by humphd** [comment]
I would separate them into their own try/catch blocks.

**Comment by mqnguyen5** [comment]
I see. Also, in the `catch` part for the removing function, should I leave it empty?

**Comment by humphd** [comment]
Yeah, that works.  I would include a comment so that future readers of the code know that you meant to do that:

```js
catch(err) {
  // intentionally ignoring this error so it fails silently
}
...
```

**Comment by mqnguyen5** [comment]
Thanks for the feedback. I have updated everything so it should be okay now.
