### ISSUE TITLE
Add initial support for Markdown 

### ISSUE THREAD

**Issue by hlavu** [mqnguyen5/mini-ssg#7]
Hi Quan, I'd like to work on your repo.

I'm going to:

- [x]  Modify the file handling so it will accept the ".md" extension.
- [x] Render Heading 1.
- [x] Render Heading 2.
- [x] Render Link.
- [x] Update README.md to add documentation for Markdown support.

If you have any requests, please let me know.

**Comment by mqnguyen5** [comment]
Sounds good. For the file handling, I suggest you use `Array.filter()` like how I did to filter out the markdown files. This shouldn't take a lot of work so you can focus on the markdown implementations

**Comment by hlavu** [comment]
Yes, I modified a bit in the `inputProcess.js` file, so it will accept the ".md" files then I almost work in `generateHTML.js`. Thanks for your suggestion.

Input is a folder
```
 const textFiles = entries.filter((entry) => {
        return (
          statSync(path.join(inputPath, entry)).isFile() &&
          (path.extname(entry) === ".txt" || path.extname(entry) === ".md") // adds ".md" extension
        );
      });
      textFiles.forEach((file) => {
        generateHTMLFile(path.join(inputPath, file), stylesheetURL);
      });
      return;
```

Input is a file
```
 // adds ".md" extension
  if (path.extname(inputPath) === ".txt" || path.extname(inputPath) === ".md") {
    generateHTMLFile(inputPath, stylesheetURL);
    return;
  }
```
